SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO Artistas VALUES(NULL,'Duki',14170000,20,'Ameri','Trap','Argentino','resources/imagenes/Duki.jpeg');
INSERT INTO Artistas VALUES(NULL,'Bad Bunny',83906000,25,'YHLQMDLG','Reggaeton','Puertorriqueño','resources/imagenes/BadBunny.jpeg');
INSERT INTO Artistas VALUES(NULL,'Quevedo',28229000,23,'BUENAS NOCHES','Reggaeton','Español','resources/imagenes/Quevedo.jpeg');
INSERT INTO Artistas VALUES(NULL,'Morat',14189000,17,'Sobre el Amor y Sus Efectos Secundarios','Pop Latino','Colombiano','resources/imagenes/Morat.jpeg');
INSERT INTO Artistas VALUES(NULL,'Eminem',72486000,20,'The Eminem Show','Rap','Estado unidense','resources/imagenes/Eminem.jpeg');
INSERT INTO Artistas VALUES(NULL,'Travis Scott',59813000,23,'ASTROWORLD','Rap','Estado unidense','resources/imagenes/TravisScott.jpeg');
INSERT INTO Artistas VALUES(NULL,'Rosalia',35813000,20,'LUX','Pop','Española','resources/imagenes/Rosalia.jpeg');
INSERT INTO Artistas VALUES(NULL,'Aitana',12419000,16,'11 RAZONES','Pop','Española','resources/imagenes/Aitana.jpeg');
INSERT INTO Artistas VALUES(NULL,'Eladio Carrion',18222000,27,'Sauce Boyz 2','Trap','Puertorriqueño','resources/imagenes/EladioCarrion.jpeg');
INSERT INTO Artistas VALUES(NULL,'Melendi',8734000,18,'Yo me veo contigo','Pop','Español','resources/imagenes/Melendi.jpeg');
INSERT INTO Artistas VALUES(NULL,'Nicki Nicole',15784000,15,'ALMA','Pop urbano','Argentina','resources/imagenes/NickiNicole.jpeg');
INSERT INTO Artistas VALUES(NULL,'Mora',19465000,19,'Paraiso','Reggaeton','Puertorriqueño','resources/imagenes/Mora.jpeg');
INSERT INTO Artistas VALUES(NULL,'Ed Sheeran',96294000,20,'Divide','Pop','Britanico','resources/imagenes/EdSheeran.jpeg');
INSERT INTO Artistas VALUES(NULL,'Rels B',24720000,20,'Flakk Daniels LP','Pop','Español','resources/imagenes/RelsB.jpeg');
INSERT INTO Cancion VALUES(NULL,'Leitmotiv','Duki','Ameri','Interludio',8950000,85,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Nueva Era','Duki, Myke Towers','Ameri','Trap',165581000,217,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Brindis','Duki, Headi One','Ameri','Trap',22878000,180,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Buscarte Lejos','Duki','Ameri','Pop',35590000,194,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Imperio','Duki, Judeline','Ameri','Pop',42032000,168,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Hardaway','Duki, YG, Eladio Carrion','Ameri','Trap',27006000,216,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Cine','Duki','Ameri','Pop',33362000,142,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Vida de Rock','Duki, Milo j','Ameri','Pop',55760000,181,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'No Drama','Duki, Ovi, Lucho SSJ','Ameri','Trap',23812000,174,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Un Día Más','Duki, YSY A','Ameri','Trap',22848000,165,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Trato de Estar Bien','Duki, Morad','Ameri','Pop',19956000,213,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Wake Up & Bake Up','Duki, Wiz Khalifa, Arcangel','Ameri','Pop',22676000,206,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Constelación','Duki, Lia Kali','Ameri','Pop',34842000,200,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Ameri','Duki','Ameri','Trap',45166000,199,'resources/imagenes/Ameri.jpg');
INSERT INTO Cancion VALUES(NULL,'Malbec','Duki, Bizarap','Desde el fin del Mundo','Trap',252539000,175,'resources/imagenes/Malbec.jpg');
INSERT INTO Cancion VALUES(NULL,'Goteo','Duki','','Trap',386372000,164,'resources/imagenes/Goteo.jpg');
INSERT INTO Cancion VALUES(NULL,'Rockstar','Duki','','Trap',255793000,112,'resources/imagenes/Rockstar.jpg');
INSERT INTO Cancion VALUES(NULL,'Rockstar 2.0','Duki','Antes de Ameri','Trap',103611000,173,'resources/imagenes/Rockstar2.jpg');
INSERT INTO Cancion VALUES(NULL,'Givenchy','Duki','','Trap',308260000,182,'resources/imagenes/Givenchy.jpg');
INSERT INTO Cancion VALUES(NULL,'Si Veo a Tu Mamá','Bad Bunny','YHLQMDLG','Urbano',1024696000,170,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'La Difícil','Bad Bunny','YHLQMDLG','Urbano',804172000,163,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Pero Ya No','Bad Bunny','YHLQMDLG','Urbano',317272000,160,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'La Santa','Bad Bunny, Daddy Yankee','YHLQMDLG','Urbano',1177931000,206,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Yo Perreo Sola','Bad Bunny','YHLQMDLG','Urbano',837760000,172,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Bichiyal','Bad Bunny, Yaviah','YHLQMDLG','Urbano',509524000,196,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Soliá','Bad Bunny','YHLQMDLG','Urbano',401846000,159,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'La Zona','Bad Bunny','YHLQMDLG','Urbano',439257000,136,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Qué Malo','Bad Bunny, Ñengo Flow','YHLQMDLG','Urbano',383352000,167,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Vete','Bad Bunny','YHLQMDLG','Urbano',1137342000,192,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Ignorantes','Bad Bunny, Sech','YHLQMDLG','Urbano',752870000,210,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'A Tu Merced','Bad Bunny','YHLQMDLG','Urbano',921960000,175,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Una Vez','Bad Bunny, Mora','YHLQMDLG','Urbano',731528000,232,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Safaera','Bad Bunny,Jowell & Randy, Ñengo Flow','YHLQMDLG','Urbano',1018707000,295,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'25 8','Bad Bunny','YHLQMDLG','Urbano',324530000,243,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Está Cabrón Ser Yo','Bad Bunny, Anuel AA','YHLQMDLG','Urbano',263814000,227,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Puesto Pa Guerrial','Bad Bunny, Myke Towers','YHLQMDLG','Urbano',117030000,190,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'P FKN R','Bad Bunny,Kendo Kaponi & Arcángel','YHLQMDLG','Urbano',149190000,258,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Hablamos Mañana','Bad Bunny, Duki, Pablo Chill-E','YHLQMDLG','Urbano',281392000,240,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'3','Bad Bunny','YHLQMDLG','Urbano',242451000,157,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Cancion VALUES(NULL,'Yonaguni','Bad Bunny','','Urbano',1604310000,206,'resources/imagenes/Yonaguni.jpg');
INSERT INTO Cancion VALUES(NULL,'La canción','Bad Bunny, J Balvin','OASIS','Urbano',2357475000,242,'resources/imagenes/LaCancion.jpg');
INSERT INTO Cancion VALUES(NULL,'Where She Goes','Bad Bunny','nadie sabe lo que va a pasar mañana','Urbano',932229000,231,'resources/imagenes/WhereSheGoes.jpg');
INSERT INTO Cancion VALUES(NULL,'Moscow Mule','Bad Bunny','Un Verano Sin Ti','Urbano',1498507000,245,'resources/imagenes/MoscowMule.jpg');
INSERT INTO Cancion VALUES(NULL,'DtMF','Bad Bunny','deBÍ TiRAR MáS FOToS','Urbano',1304984000,237,'resources/imagenes/DtMF.jpg');
INSERT INTO Cancion VALUES(NULL,'KASSANDRA','Quevedo','BUENAS NOCHES','Reggeaton',63413000,183,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'DURO','Quevedo','BUENAS NOCHES','Reggeaton',40880000,162,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'IGUALES','Quevedo','BUENAS NOCHES','Reggeaton',45689000,183,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'GRAN VÍA','Quevedo, Aitana','BUENAS NOCHES','Reggeaton',144319000,213,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'CHAPIADORA.COM','Quevedo','BUENAS NOCHES','Reggeaton',46835000,197,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'POR ATRÁS','Quevedo','BUENAS NOCHES','Reggeaton',26213000,171,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'14 FEBREROS','Quevedo, Sin Nombre','BUENAS NOCHES','Reggeaton',22313000,172,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'LA 125','Quevedo, Yung Beef','BUENAS NOCHES','Reggeaton',18968000,194,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'HALO','Quevedo, La Pantera','BUENAS NOCHES','Reggeaton',97232000,181,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'MR. MOONDIAL','Quevedo, Pitbull','BUENAS NOCHES','Reggeaton',74744000,165,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'QUÉ ASCO DE TODO','Quevedo','BUENAS NOCHES','Reggeaton',11236000,190,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'NOEMÚ','Quevedo','BUENAS NOCHES','Reggeaton',19676000,206,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'SHIBATTO','Quevedo','BUENAS NOCHES','Reggeaton',60285000,138,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'LOS DÍAS CONTADOS','Quevedo, Rels B','BUENAS NOCHES','Reggeaton',50731000,161,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'EL ESTRIBILLO','Quevedo','BUENAS NOCHES','Reggeaton',15998000,161,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'AMANECIÓ','Quevedo,De La Rose, De La Ghetto','BUENAS NOCHES','Reggeaton',50931000,255,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'TE FALLÉ','Quevedo,Sech','BUENAS NOCHES','Reggeaton',22530000,219,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'BUENAS NOCHES','Quevedo','BUENAS NOCHES','Reggeaton',29219000,238,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'Soleao','Quevedo, Myke Towers','','Reggeaton',205602000,218,'resources/imagenes/Soleao.jpg');
INSERT INTO Cancion VALUES(NULL,'La Última','Quevedo','','Reggeaton',59653000,170,'resources/imagenes/LaUltima.jpg');
INSERT INTO Cancion VALUES(NULL,'Columbia','Quevedo','','Reggeaton',1083903000,186,'resources/imagenes/Columbia.jpg');
INSERT INTO Cancion VALUES(NULL,'El Tonto','Quevedo, Lola Indigo','','Reggeaton',240631000,188,'resources/imagenes/ElTonto.jpg');
INSERT INTO Cancion VALUES(NULL,'Playa del Inglés','Quevedo, Myke Towers','Donde Quiero Estar','Reggeaton',458513000,237,'resources/imagenes/PlayaDelIngles.jpg');
INSERT INTO Cancion VALUES(NULL,'Mi Nuevo Vicio','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',133027000,237,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'En un Solo Dia','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',191039000,202,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Aprender a quererte','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',354471000,229,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Yo mas te adoro','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',55247000,202,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Di que no te vas','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',57278000,238,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Como te atreves','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',568615000,240,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Una vez mas','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',33999000,241,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Mil Tormentas','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',137556000,233,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Ahora que no puedo hablar','Sobre el Amor y Sus Efectos Secundarios','Morat','Pop',31558000,264,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Cuanto me duele','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',129667000,230,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Ya no estas tu','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',38107000,199,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Mi nuevo vicio','Morat','Sobre el Amor y Sus Efectos Secundarios','Pop',127463000,241,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Cancion VALUES(NULL,'Amor con Hielo','Morat','Sobre el Amor y Sus Efectos Secundarios... Y unas cuantas cosas mas','Pop',248507,203,'resources/imagenes/AmorConHielo.jpg');
INSERT INTO Cancion VALUES(NULL,'Yo Contigo, Tú Conmigo','Morat, Álvaro Soler','Sobre el Amor y Sus Efectos Secundarios... Y unas cuantas cosas mas','Pop',128918000,173,'resources/imagenes/YoContigoTuConmigo.jpg');
INSERT INTO Cancion VALUES(NULL,'París','Morat, Duki','','Pop',228425,182,'resources/imagenes/Paris.jpg');
INSERT INTO Cancion VALUES(NULL,'Besos en Guerra','Morat, Juanes','Balas perdidas','Pop',771028000,231,'resources/imagenes/BesosEnGuerra.jpeg');
INSERT INTO Cancion VALUES(NULL,'Porfa No Te Vayas','Morat, Beret','','Pop',303167000,209,'resources/imagenes/PorfaNoTeVayas.jpeg');
INSERT INTO Cancion VALUES(NULL,'Curtains Up (Skit)','Eminem','The Eminem Show','Hip-Hop',439000,29,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'White America','Eminem','The Eminem Show','Hip-Hop',198202000,324,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Business','Eminem','The Eminem Show','Hip-Hop',264841000,251,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Cleanin Out My Closet','Eminem','The Eminem Show','Hip-Hop',513269000,397,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Square Dance','Eminem','The Eminem Show','Hip-Hop',95884000,523,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'The Kiss (Skit)','Eminem','The Eminem Show','Hip-Hop',28653000,75,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Soldier','Eminem','The Eminem Show','Hip-Hop',146189000,226,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Say Goodbye Hollywood','Eminem','The Eminem Show','Hip-Hop',72775000,272,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Drips','Eminem, Obie Trice','The Eminem Show','Hip-Hop',52542000,0,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Without Me','Eminem','The Eminem Show','Hip-Hop',2926549000,290,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Paul Rosenberg (Skit)','Eminem','The Eminem Show','Hip-Hop',72000,22,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Sing for the Moment','Eminem','The Eminem Show','Hip-Hop',673488000,339,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Superman','Eminem, Dina Rae','The Eminem Show','Hip-Hop',1297328000,350,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Hailies Song','Eminem','The Eminem Show','Hip-Hop',163465000,320,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Steve Berman (Skit)','Eminem','The Eminem Show','Hip-Hop',23282000,33,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'When the Music Stops','Eminem, D12','The Eminem Show','Hip-Hop',97816000,269,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Say What You Say','Eminem, Dr. Dre','The Eminem Show','Hip-Hop',58212000,309,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Till I Collapse','Eminem, Nate Dogg','The Eminem Show','Hip-Hop',2402280000,297,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'My Dads Gone Crazy','Eminem, Hailie Jade','The Eminem Show','Hip-Hop',108857000,267,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'Curtains Close (Skit)','Eminem','The Eminem Show','Hip-Hop',12746000,61,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Cancion VALUES(NULL,'The Real Slim Shady','Eminem','The Marshall Mathers LP','Hip-Hop',2362555000,284,'resources/imagenes/TheRealSlimShady.jpg');
INSERT INTO Cancion VALUES(NULL,'Lose Yourself','Eminem','SHADYXV','Hip-Hop',2781925000,320,'resources/imagenes/LoseYourself.jpg');
INSERT INTO Cancion VALUES(NULL,'The Monster','Eminem, Rihanna','The Marshall Mathers LP2','Hip-Hop',1337491000,250,'resources/imagenes/TheMonster.jpg');
INSERT INTO Cancion VALUES(NULL,'Godzilla','Eminem, Juice WRLD','Music to be murdered by','Hip-Hop',1834682997,210,'resources/imagenes/Godzilla.jpg');
INSERT INTO Cancion VALUES(NULL,'Mockingbird','Eminem','Encore','Hip-Hop',2357071000,250,'resources/imagenes/Mockingbird.jpg');
INSERT INTO Cancion VALUES(NULL,'STARGAZING','Travis Scott','ASTROWORLD','Hip-Hop',861055000,270,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'CAROUSEL','Travis Scott','ASTROWORLD','Hip-Hop',244726000,180,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'SICKO MODE','Travis Scott','ASTROWORLD','Hip-Hop',2519252000,312,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'R.I.P. SCREW','Travis Scott','ASTROWORLD','Hip-Hop',255254000,185,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'STOP TRYING TO BE GOD','Travis Scott','ASTROWORLD','Hip-Hop',297065000,338,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'NO BYSTANDERS','Travis Scott','ASTROWORLD','Hip-Hop',455838000,218,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'SKELETONS','Travis Scott','ASTROWORLD','Hip-Hop',513124000,145,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'WAKE UP','Travis Scott','ASTROWORLD','Hip-Hop',37454100,231,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'5% TINT','Travis Scott','ASTROWORLD','Hip-Hop',661130000,196,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'NC-17','Travis Scott','ASTROWORLD','Hip-Hop',190446000,156,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'ASTROTHUNDER','Travis Scott','ASTROWORLD','Hip-Hop',546200000,142,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'YOSEMITE','Travis Scott','ASTROWORLD','Hip-Hop',784145000,150,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'CANT SAY','Travis Scott','ASTROWORLD','Hip-Hop',848248000,198,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'WHO WHAT!','Travis Scott','ASTROWORLD','Hip-Hop',243572000,176,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'BUTTERFLY EFFECT','Travis Scott','ASTROWORLD','Hip-Hop',1848259000,190,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'HOUSTONFORNICATION','Travis Scott','ASTROWORLD','Hip-Hop',300554000,217,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'COFFEE BEAN','Travis Scott','ASTROWORLD','Hip-Hop',268442000,209,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Cancion VALUES(NULL,'Goosebumps','Travis Scott','Birds in the trap sing McKnight','Hip-Hop',3042923000,243,'resources/imagenes/Goosebumps.jpg');
INSERT INTO Cancion VALUES(NULL,'FE!N','Travis Scott, Playboi Carti','UTOPIA','Hip-Hop',1504397000,191,'resources/imagenes/Fein.jpg');
INSERT INTO Cancion VALUES(NULL,'HIGHEST IN THE ROOM','Travis Scott','','Hip-Hop',2194780000,175,'resources/imagenes/HighestInTheRoom.jpg');
INSERT INTO Cancion VALUES(NULL,'OUT WEST','Travis Scott, Young Thug, JACKBOYS','JACKBOYS','Hip-Hop',864688000,157,'resources/imagenes/OutWest.jpg');
INSERT INTO Cancion VALUES(NULL,'HYAENA','Travis Scott','UTOPIA','Hip-Hop',206011000,222,'resources/imagenes/Hyaena.jpg');
INSERT INTO Cancion VALUES(NULL,'Sexo Violencia y Llantas','Rosalía','LUX','Pop',51589000,140,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Reliquia','Rosalía','LUX','Pop',66380000,230,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Divinize','Rosalía','LUX','Pop',42359000,243,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Porcelana','Rosalía, Dougie F','LUX','Pop',36699000,248,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Mio Cristo Piange Diamanti','Rosalía','LUX','Pop',32476000,269,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Berghain','Rosalía, Björk, Yves Tumor','LUX','Pop',111407000,178,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'La Perla','Rosalía, Yahritza Y Su Esencia','LUX','Pop',174260000,195,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Mundo Nuevo','Rosalía','LUX','Pop',28574000,140,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'De Madrugá','Rosalía','LUX','Pop',32878000,104,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Dios Es Un Stalker','Rosalía','LUX','Pop',45455000,130,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'La Yugular','Rosalía','LUX','Pop',37890000,258,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Sauvignon Blanc','Rosalía','LUX','Pop',30998000,162,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'La Rumba Del Perdón','Rosalía, Estrella Morente, Sílvia Pérez Cruz','LUX','Pop',29690000,251,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Memória','Rosalía, Carminho','LUX','Pop',23823000,225,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'Magnolias','Rosalía','LUX','Pop',31461000,194,'resources/imagenes/Lux.jpg');
INSERT INTO Cancion VALUES(NULL,'SAOKO','Rosalía','MOTOMAMI','Pop',227269000,137,'resources/imagenes/Saoko.jpg');
INSERT INTO Cancion VALUES(NULL,'DESPECHÁ','Rosalía','','Pop',1257877000,157,'resources/imagenes/Despecha.jpg');
INSERT INTO Cancion VALUES(NULL,'TKN','Rosalía, Travis Scott','','Pop',498439000,129,'resources/imagenes/TKN.jpg');
INSERT INTO Cancion VALUES(NULL,'Con Altura','Rosalía, J Balvin, El Guincho','','Pop',844502000,161,'resources/imagenes/ConAltura.jpg');
INSERT INTO Cancion VALUES(NULL,'Malamente','Rosalía','El mal querer','Pop',329861000,150,'resources/imagenes/Malamente.jpg');
INSERT INTO Cancion VALUES(NULL,'No Te Has Ido y Ya Te Extraño','Aitana','11 RAZONES','Pop',25013000,210,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'- (MENOS)','Aitana, Alvaro Diaz, Pole','11 RAZONES','Pop',15032000,188,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'Estupidez','Aitana','11 RAZONES','Pop',18927000,153,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'X (Por)','Aitana','11 RAZONES','Pop',12422000,141,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'Corazón Sin Vida','Aitana, Sebastián Yatra','11 RAZONES','Pop',128290000,181,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'÷ (Dividido)','Aitana','11 RAZONES','Pop',10109000,195,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'Cuando Te Fuiste','Aitana, Natalia Lacunza','11 RAZONES','Pop',29693000,167,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'+ (Más)','Aitana, Cali y El Dandee','11 RAZONES','Pop',61369000,219,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'Si No Vas a Volver','Aitana','11 RAZONES','Pop',61369000,155,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'= (Igual)','Aitana','11 RAZONES','Pop',17392000,224,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'11 Razones','Aitana','11 RAZONES','Pop',52460000,213,'resources/imagenes/11Razones.jpg');
INSERT INTO Cancion VALUES(NULL,'Mon Amour','Aitana, Zzoilo','','Pop',847073000,179,'resources/imagenes/MonAmour.jpg');
INSERT INTO Cancion VALUES(NULL,'Formentera','Aitana, Nicki Nicole','alpha','Pop',233665000,207,'resources/imagenes/Formentera.jpg');
INSERT INTO Cancion VALUES(NULL,'Gran Vía','Aitana, Quevedo','Buenas noches','Pop',144319000,213,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Cancion VALUES(NULL,'Presiento','Aitana, Morat','Balas perdidas','Pop',396695000,174,'resources/imagenes/Presiento.jpg');
INSERT INTO Cancion VALUES(NULL,'Vas A Quedarte','Aitana','Spoiler','Pop',211440000,226,'resources/imagenes/VasAQuedarte.jpg');
INSERT INTO Cancion VALUES(NULL,'Par de Tenis','Eladio Carrión','Sauce Boyz 2','Urbano',25028000,181,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Claro Cristal','Eladio Carrión','Sauce Boyz 2','Urbano',52046000,161,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'No Te Deseo el Mal','Eladio Carrión, Karol G','Sauce Boyz 2','Urbano',195827000,232,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Flores en Anónimo','Eladio Carrión','Sauce Boyz 2','Urbano',140785000,170,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Fuego','Eladio Carrión','Sauce Boyz 2','Urbano',19619000,155,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Miradas Raras','Eladio Carrión, Sech','Sauce Boyz 2','Urbano',21048000,195,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Me Gustas Natural','Eladio Carrión, Rels B','Sauce Boyz 2','Urbano',364305000,170,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Quienes Son Ustedes','Eladio Carrión','Sauce Boyz 2','Urbano',19401000,140,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Alejarme de Ti','Eladio Carrión, Jay Wheeler','Sauce Boyz 2','Urbano',48705000,233,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Gastar','Eladio Carrión','Sauce Boyz 2','Urbano',12544000,149,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Hola Como Vas','Eladio Carrión','Sauce Boyz 2','Urbano',310212,198,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Sin Frenos','Eladio Carrión, Bizarrap, Duki','Sauce Boyz 2','Urbano',198882000,211,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Socio','Eladio Carrión, Luar La L','Sauce Boyz 2','Urbano',58718000,253,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Jóvenes Millonarios','Eladio Carrión, Myke Towers','Sauce Boyz 2','Urbano',119803000,182,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'No Me Importa un Carajo','Eladio Carrión, Ovi','Sauce Boyz 2','Urbano',16081000,190,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Mami Dijo','Eladio Carrión','Sauce Boyz 2','Urbano',16495000,133,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Cheque','Eladio Carrión, Jon Z, Noriel','Sauce Boyz 2','Urbano',23701000,210,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Como Sea','Eladio Carrión, Arcángel','Sauce Boyz 2','Urbano',20154000,202,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Primera Vez','Eladio Carrión, Nicky Jam','Sauce Boyz 2','Urbano',14413000,189,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Cuarentena','Eladio Carrión','Sauce Boyz 2','Urbano',41770000,131,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Touch Your Body','Eladio Carrión','Sauce Boyz 2','Urbano',25123000,147,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Sauce Boy Freestyle 5','Eladio Carrión','Sauce Boyz 2','Urbano',34581000,176,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Cancion VALUES(NULL,'Mbappé','Eladio Carrión','SEN2 KBRN VOL.2','Urbano',281183000,147,'resources/imagenes/Mbappe.jpg');
INSERT INTO Cancion VALUES(NULL,'Coco Chanel','Eladio Carrión','3MEN2 KBRN','Urbano',582999000,208,'resources/imagenes/CocoChanel.jpg');
INSERT INTO Cancion VALUES(NULL,'Kemba Walker','Eladio Carrión, Bad Bunny','','Urbano',453931000,152,'resources/imagenes/KembaWalker.jpg');
INSERT INTO Cancion VALUES(NULL,'Si La Calle Llama','Eladio Carrión','3MEN2 KBRN','Urbano',244100000,240,'resources/imagenes/SiLaCalleLLama.jpg');
INSERT INTO Cancion VALUES(NULL,'Özil','Eladio Carrión','DON KBRN','Urbano',8160000,159,'resources/imagenes/Ozil.jpg');
INSERT INTO Cancion VALUES(NULL,'Con la luna llena','Melendi','Yo me veo contigo','Pop',74719000,228,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Con solo una sonrisa','Melendi','Yo me veo contigo','Pop',75603000,229,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Loco','Melendi','Yo me veo contigo','Pop',32363000,211,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Piratas del bar caribe','Melendi','Yo me veo contigo','Pop',37322000,244,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Como una vela','Melendi','Yo me veo contigo','Pop',35151000,220,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Llueve','Melendi','Yo me veo contigo','Pop',18237000,239,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Canción de amor caducada','Melendi','Yo me veo contigo','Pop',47531000,248,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Lágrimas desordenadas','Melendi','Yo me veo contigo','Pop',111504000,229,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Cheque al portamor','Melendi','Yo me veo contigo','Pop',122144000,295,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Aprendiz de caballero','Melendi','Yo me veo contigo','Pop',21670000,243,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'La religión de los idiotas','Melendi','Yo me veo contigo','Pop',24571000,208,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Tocado y hundido','Melendi','Yo me veo contigo','Pop',103331000,211,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Desde que estamos juntos','Melendi','Yo me veo contigo','Pop',113741000,274,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'La casa no es igual','Melendi','Yo me veo contigo','Pop',41989000,213,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'Existen los ángeles','Melendi','Yo me veo contigo','Pop',10464000,261,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Cancion VALUES(NULL,'El Nano','Melendi','','Pop',16911000,169,'resources/imagenes/ElNano.jpg');
INSERT INTO Cancion VALUES(NULL,'Un violinista en tu Tejado','Melendi','Curiosa la cara de tu padre','Pop',215127000,222,'resources/imagenes/ViolinistaEnTuTejado.jpg');
INSERT INTO Cancion VALUES(NULL,'Caminando por la Vida','Melendi','QUe el cielo espere sentao...','Pop',191322000,211,'resources/imagenes/CaminandoPorLaVida.jpg');
INSERT INTO Cancion VALUES(NULL,'Barbie de Extrarradio','Melendi','Volvamos a empezar','Pop',93102000,215,'resources/imagenes/BarbieDeExtrradio.jpeg');
INSERT INTO Cancion VALUES(NULL,'La Promesa','Melendi','Un alumno más','Pop',249386000,233,'resources/imagenes/LaPromesa.jpg');
INSERT INTO Cancion VALUES(NULL,'Ya No','Nicki Nicole','ALMA','Pop',8029000,171,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'Dispara','Nicki Nicole, Milo j','ALMA','Pop',252148000,143,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'No Voy a Llorar','Nicki Nicole','ALMA','Pop',42981000,178,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'8 AM','Nicki Nicole, Young Miko','ALMA','Pop',173769000,147,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'Se Va 1 Llegan 2','Nicki Nicole','ALMA','Pop',12623000,143,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'Llámame','Nicki Nicole','ALMA','Pop',14661000,124,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'Qué Le Pasa Conmigo','Nicki Nicole, Rels B','ALMA','Pop',276228000,167,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'Tuyo (Cover)','Nicki Nicole','ALMA','Pop',6970000,133,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'Caen Las Estrellas','Nicki Nicole, YSY A','ALMA','Pop',66218000,145,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'Tienes Mi Alma','Nicki Nicole','ALMA','Pop',5959000,127,'resources/imagenes/Alma.jpg');
INSERT INTO Cancion VALUES(NULL,'We Love That Shit','Nicki Nicole, KHEA','Naiki','Urbano',14456000,170,'resources/imagenes/WeLoveThatShit.jpg');
INSERT INTO Cancion VALUES(NULL,'Máscara','Nicki Nicole, Duki','Naiki','Urbano',20866000,145,'resources/imagenes/Mascara.jpg');
INSERT INTO Cancion VALUES(NULL,'Colocao','Nicki Nicole','','Urbano',146979000,179,'resources/imagenes/Colocao.jpg');
INSERT INTO Cancion VALUES(NULL,'Mamichula','Nicki Nicole, Trueno','Atrevido','Urbano',685954000,219,'resources/imagenes/Mamichula.jpg');
INSERT INTO Cancion VALUES(NULL,'Dangerous','Nicki Nicole, Trueno, Bizarap','Parte de mí','Urbano',53352000,159,'resources/imagenes/Dangerous.jpg');
INSERT INTO Cancion VALUES(NULL,'Bienvenida al Paraíso','Mora','Paraiso','Urbano',19740000,103,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Domingo de Bote','Mora','Paraiso','Urbano',149041000,190,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'APA','Mora, Quevedo','Paraiso','Urbano',193922000,199,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Calentón','Mora','Paraiso','Urbano',135838000,202,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Cositas','Mora, paopao','Paraiso','Urbano',39509000,195,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'En la Orilla','Mora','Paraiso','Urbano',48636000,235,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Modelito','Mora,YOVNGCHIMI','Paraiso','Urbano',314001000,190,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Casualidad','Mora','Paraiso','Urbano',78598000,183,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Airbnb','Mora, De La Ghetto','Paraiso','Urbano',53055000,185,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Tú Sabes Dónde Vivo','Mora','Paraiso','Urbano',28551000,170,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Eivissa','Mora, Danny Ocean','Paraiso','Urbano',34116000,200,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Cómo Has Estau','Mora','Paraiso','Urbano',214952000,127,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Malafama','Mora','Paraiso','Urbano',19872000,169,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Qué Habilidad','Mora','Paraiso','Urbano',82838000,233,'resources/imagenes/Paraiso.jpg');
INSERT INTO Cancion VALUES(NULL,'Detrás de Tu Alma','Mora','Lo mismo de siempre','Urbano',130750000,237,'resources/imagenes/DetrasDeTuAlma.jpg');
INSERT INTO Cancion VALUES(NULL,'Reina','Mora, SAIKO','ESTRELLA','Urbano',261194000,211,'resources/imagenes/Reina.jpg');
INSERT INTO Cancion VALUES(NULL,'Diamonds','Mora, Dei V','ESTRELLA','Urbano',75809000,193,'resources/imagenes/Diamonds.jpg');
INSERT INTO Cancion VALUES(NULL,'Memorias','Mora, JHAYCO','MICRODOSIS','Urbano',477499000,228,'resources/imagenes/Memorias.jpg');
INSERT INTO Cancion VALUES(NULL,'La Inocente','Mora, Feid','MICRODOSIS','Urbano',987501000,202,'resources/imagenes/LaInocente.jpg');
INSERT INTO Cancion VALUES(NULL,'Eraser','Ed Sheeran','Divide','Pop',215952000,227,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Castle on the Hill','Ed Sheeran','Divide','Pop',1553495000,261,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Dive','Ed Sheeran','Divide','Pop',841433000,238,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Shape of You','Ed Sheeran','Divide','Pop',4732328000,233,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Perfect','Ed Sheeran','Divide','Pop',3794692000,263,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Galway Girl','Ed Sheeran','Divide','Pop',1543678000,170,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Happier','Ed Sheeran','Divide','Pop',1464793000,207,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'New Man','Ed Sheeran','Divide','Pop',342877000,189,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Hearts Dont Break Around Here','Ed Sheeran','Divide','Pop',287891000,248,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'What Do I Know','Ed Sheeran','Divide','Pop',422286000,237,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'How Would You Feel (Paean)','Ed Sheeran','Divide','Pop',393800000,280,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Supermarket Flowers','Ed Sheeran','Divide','Pop',830685000,221,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Barcelona','Ed Sheeran','Divide','Pop',327309000,191,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Bibia Be Ye Ye','Ed Sheeran','Divide','Pop',236771000,176,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Nancy Mulligan','Ed Sheeran','Divide','Pop',321460000,179,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'Save Myself','Ed Sheeran','Divide','Pop',254017000,247,'resources/imagenes/Divide.jpg');
INSERT INTO Cancion VALUES(NULL,'I Dont Care','Ed Sheeran, Justin Bieber','+-=/x','Pop',2110848000,219,'resources/imagenes/IDontCare.jpeg');
INSERT INTO Cancion VALUES(NULL,'Shivers','Ed Sheeran','=','Pop',1980637000,217,'resources/imagenes/Shivers.jpeg');
INSERT INTO Cancion VALUES(NULL,'Sapphire','Ed Sheeran','Play','Pop',297700000,179,'resources/imagenes/Sapphire.jpeg');
INSERT INTO Cancion VALUES(NULL,'Merry Christmas','Ed Sheeran, Elton John','','Pop',383568000,208,'resources/imagenes/MerryChristmas.jpeg');
INSERT INTO Cancion VALUES(NULL,'Photograph','Ed Sheeran','x','Pop',3264447000,258,'resources/imagenes/Photograph.jpeg');
INSERT INTO Cancion VALUES(NULL,'Open Your Eyes','Rels B','Flakk Daniels LP','Urbano',14444000,74,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Love It','Rels B','Flakk Daniels LP','Urbano',156482000,189,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Es Mejor','Rels B','Flakk Daniels LP','Urbano',108332000,179,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Reina de Pikas','Rels B','Flakk Daniels LP','Urbano',110461000,191,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Diles','Rels B','Flakk Daniels LP','Urbano',128707000,185,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Buenos Genes','Rels B, DELLAFUENTE','Flakk Daniels LP','Urbano',313607000,245,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Flakks Plan','Rels B','Flakk Daniels LP','Urbano',40060000,182,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Dime Que No','Rels B, DL Blando','Flakk Daniels LP','Urbano',14762000,220,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Lejos de Ti','Rels B','Flakk Daniels LP','Urbano',255073000,194,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Si Me Muero','Rels B','Flakk Daniels LP','Urbano',35608000,105,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Cancion VALUES(NULL,'Tu Vas Sin (Fav)','Rels B','afroLOVA 25','Urbano',346142000,110,'resources/imagenes/TuVasSin.jpg');
INSERT INTO Cancion VALUES(NULL,'A Mí','Rels B','','Urbano',960081000,209,'resources/imagenes/AMi.jpg');
INSERT INTO Cancion VALUES(NULL,'Tienes el Don','Rels B','Inéditos','Urbano',199017000,241,'resources/imagenes/TienesElDon.jpg');
INSERT INTO Cancion VALUES(NULL,'Cómo Dormiste','Rels B','','Urbano',706502000,112,'resources/imagenes/ComoDormiste.jpg');
INSERT INTO Cancion VALUES(NULL,'Sin Mirar las Señales','Rels B','Happy Birthday Flakko','Urbano',263223000,240,'resources/imagenes/SinMirarLasSeñales.jpg');
INSERT INTO Album VALUES(NULL,'AMERI','Duki','Leitmotiv, Nueva Era, Brindis, Buscarte Lejos, Imperio, Hardaway, Cine, Vida de Rock, No Drama, Barro, Un Día Más, Trato de estar bien, Wake up & Bake up, Constelación, Ameri','Trap',20120000,2748,15,'resources/imagenes/Ameri.jpg');
INSERT INTO Album VALUES(NULL,'YHLQMDLG','Bad Bunny','Si Veo a Tu Mamá, La Difícil, Pero Ya No, La Santa, Yo Perreo Sola, Bichiyal, Soliá, La Zona, Qué Malo, Vete, Ignorantes, A Tu Merced, Una Vez, Safaera, 25 8, Está Cabrón Ser Yo, Puesto Pa Guerrial, P FKN R, Hablamos Mañana, 3',' Urbano',125123000,3900,20,'resources/imagenes/YHLQMDLG.jpg');
INSERT INTO Album VALUES(NULL,'BUENAS NOCHES','Quevedo','KASSANDRA, DURO, IGUALES, GRAN VÍA, CHAPIADORA.COM, POR ATRÁS, 14 FEBREROS, LA 125, HALO, MR. MOONDIAL, QUÉ ASCO DE TODO, NOEMÚ, SHIBATTO, LOS DÍAS CONTADOS, EL ESTRIBILLO, AMANECIÓ, TE FALLÉ, BUENAS NOCHES','Reggeaton',11360000,3397,18,'resources/imagenes/BuenasNoches.jpg');
INSERT INTO Album VALUES(NULL,'Sobre el Amor y Sus Efectos Secundarios','Morat','Mi Nuevo Vicio, En un Solo Dia, Aprender a quererte, Yo mas te adoro, Di que no te vas, Como te atreves, Una vez mas, Mil Tormentas, Ahora que no puedo hablar, Cuanto me duele, Ya no estas tu, Mi nuevo vicio','Pop',31508000,2761,12,'resources/imagenes/SobreElAmor.jpg');
INSERT INTO Album VALUES(NULL,'The Eminem Show','Eminem','Curtains Up (Skit), White America, Business, Cleanin Out My Closet, Square Dance, The Kiss (Skit), Soldier, Say Goodbye Hollywood, Drips, Without Me, Paul Rosenberg (Skit), Sing for the Moment, Superman, Hailies Song, Steve Berman (Skit), When the Music Stops, Say What You Say, Till I Collapse, My Dads Gone Crazy, Curtains Close (Skit)','Hip-Hop',57147000,4620,20,'resources/imagenes/TheEminemShow.jpg');
INSERT INTO Album VALUES(NULL,'ASTROWORLD','Travis Scott','STARGAZING, CAROUSEL, SICKO MODE, R.I.P. SCREW, STOP TRYING TO BE GOD, NO BYSTANDERS, SKELETONS, WAKE UP, 5% TINT, NC-17, ASTROTHUNDER, YOSEMITE, CANT SAY, WHO WHAT!, BUTTERFLY EFFECT, HOUSTONFORNICATION, COFFEE BEAN','Hip-Hop',18714000,3522,17,'resources/imagenes/ASTROWORLD.jpg');
INSERT INTO Album VALUES(NULL,'LUX','Rosalía','Sexo Violencia y Llantas, Reliquia, Divinize, Porcelana, Mio Cristo Piange Diamanti, Berghain, La Perla, Mundo Nuevo, De Madrugá, Dios Es Un Stalker, La Yugular, Sauvignon Blanc, La Rumba Del Perdón, Memoria, Magnolias','Pop',22814000,2975,15,'resources/imagenes/Lux.jpg');
INSERT INTO Album VALUES(NULL,'11 RAZONES','Aitana','No Te Has Ido y Ya Te Extraño, - (MENOS), Estupidez, X (Por), Corazón Sin Vida, ÷ (Dividido), Cuando Te Fuiste, + (Más), Si No Vas a Volver, = (Igual), 11 Razones','Pop',12422000,2051,11,'resources/imagenes/11Razones.jpg');
INSERT INTO Album VALUES(NULL,'Sauce Boyz 2','Eladio Carrión','Par de Tenis, Claro Cristal, No Te Deseo el Mal, Flores en Anónimo, Fuego, Miradas Raras, Me Gustas Natural, Quienes Son Ustedes, Alejarme de Ti, Gastar, Hola Como Vas, Sin Frenos, Socio, Jóvenes Millonarios, No Me Importa un Carajo, Mami Dijo, Cheque, Como Sea, Primera Vez, Cuarentena, Touch Your Body, Sauce Boy Freestyle 5','Urbano',12214000,3960,22,'resources/imagenes/SauceBoyz2.jpg');
INSERT INTO Album VALUES(NULL,'Yo me veo contigo','Melendi','Con la luna llena, Con solo una sonrisa, Loco, Piratas del bar caribe, Como una vela, Llueve, Canción de amor caducada, Lágrimas desordenadas, Cheque al portamor, Aprendiz de caballero, La religión de los idiotas, Tocado y hundido, Desde que estamos juntos, La casa no es igual, Existen los ángeles','Pop',13765000,3553,13,'resources/imagenes/YoMeVeoContigo.jpg');
INSERT INTO Album VALUES(NULL,'ALMA','Nicki Nicole','Ya No, Dispara, No Voy a Llorar, 8 AM, Se Va 1 Llegan 2, Llámame, Qué Le Pasa Conmigo, Tuyo (Cover), Caen Las Estrellas, Tienes Mi Alma','Urbano',5223000,1483,10,'resources/imagenes/Alma.jpg');
INSERT INTO Album VALUES(NULL,'Paraiso','Mora','Bienvenida al Paraíso, Domingo de Bote, APA, Calentón, Cositas, En la Orilla, Modelito, Casualidad, Airbnb, Tú Sabes Dónde Vivo, Eivissa, Cómo Has Estau, Malafama, Qué Habilidad','Urbano',19622000,2588,14,'resources/imagenes/Paraiso.jpg');
INSERT INTO Album VALUES(NULL,'Divide','Ed Sheeran','Eraser, Castle on the Hill, Dive, Shape of You, Perfect, Galway Girl, Happier, New Man, Hearts Dont Break Around Here, What Do I Know, How Would You Feel (Paean), Supermarket Flowers, Barcelona, Bibia Be Ye Ye, Nancy Mulligan, Save Myself','Pop',253722000,3573,16,'resources/imagenes/Divide.jpg');
INSERT INTO Album VALUES(NULL,'Flakk Daniels LP','Rels B','Open Your Eyes, Love It, Es Mejor, Reina de Pikas, Diles, Buenos Genes, Flakks Plan, Dime Que No, Lejos de Ti, Si Me Muero','Urbano',14444000,1768,10,'resources/imagenes/FlakkDanielLP.jpg');
INSERT INTO Podcast VALUES(NULL,'The Wild Project','Jordi Wild','Humor',1365000); 
INSERT INTO Podcast VALUES(NULL,'WorldCast','Pedro Buerbaum','Cultura',175000); 
INSERT INTO Podcast VALUES(NULL,'Offsiders','Historias del fútbol','Deportes',15000); 
INSERT INTO Podcast VALUES(NULL,'La ruina','La ruina','Humor',73000); 
INSERT INTO Podcast VALUES(NULL,'Roca Project','Carlos Roca','Cultura',322000); 
INSERT INTO Genero VALUES(Null,'Trap');
INSERT INTO Genero VALUES(Null,'Rap');
INSERT INTO Genero VALUES(Null,'Urbano');
INSERT INTO Genero VALUES(Null,'Pop');
INSERT INTO Genero VALUES(Null,'Reggaeton');
INSERT INTO Genero VALUES(Null,'Cultura');
INSERT INTO Genero VALUES(Null,'Humor');
INSERT INTO Genero VALUES(Null,'Deportes');
INSERT INTO Usuario VALUES(NULL, 'Pepito','abc123.','Mora');
SET FOREIGN_KEY_CHECKS = 1;