CREATE SCHEMA IF NOT EXISTS Spotify;
USE Spotify;

CREATE TABLE IF NOT EXISTS Artistas(
	ID int NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(20) NOT NULL,
	Reproducciones int NOT NULL,
	Cancion int NOT NULL,
	Album int NOT NULL,
	Genero VARCHAR(20) NOT NULL,
	Nacionalidad VARCHAR(20) NOT NULL,
	Imagen MEDIUMBLOB,
	UNIQUE(ID)
);
CREATE TABLE IF NOT EXISTS Cancion(
	ID int NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(130) NOT NULL,
	Artistas VARCHAR (130) NOT NULL,
	Album VARCHAR(80) NOT NULL,
	Genero VARCHAR(20) NOT NULL,
	Reproducciones int NOT NULL,
	Duracion int NOT NULL,
	Imagen MEDIUMBLOB,
	UNIQUE(ID)
);
CREATE TABLE IF NOT EXISTS Album(
	ID int NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(80) NOT NULL,
	Artistas VARCHAR(130) NOT NULL,
	Canciones VARCHAR(2000) NOT NULL,
	Genero VARCHAR(20) NOT NULL,
	Reproducciones int NOT NULL,
	Duracion int NOT NULL,
	Cantidad_Canciones int NOT NULL,
	Imagen MEDIUMBLOB,
	UNIQUE(ID)
);

CREATE TABLE IF NOT EXISTS Podcast(
	ID int NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(50) NOT NULL,
	Narradores VARCHAR(130) NOT NULL,
	Genero VARCHAR(20) NOT NULL,
	Oyentes int NOT NULL,
	UNIQUE(ID)
);

CREATE TABLE IF NOT EXISTS Genero(
	ID int NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(20) NOT NULL,
	UNIQUE(ID)
)
